<?php
ob_start();
session_start();
/**
 * Custom MVC stucture base index file
 * ================================================================
 * WARNING : Do not edit this file unless required
 * ================================================================
 * Custom MVC sturucture index file.
 *
 * @package Patpedhi
 *
 * @author Abhijeet Kinjawadekar
 * @version 1.0
 */
error_reporting(E_ALL);
/**
 * ===============================================
 * Base MVC files include
 * ===============================================
 */
require ("classes/basecontroller.php");
require ("classes/basemodel.php");
require ("classes/view.php");
require ("classes/viewmodel.php");
require ("classes/loader.php");
require ("classes/load.php");
require ("config/constants.php"); // common global constants file
require ("config/config.php"); // common global config file
require ("classes/registry.php");
$registry_obj = new Registry();
//require "language/en/user.php";
$loader = new Loader (); // create the loader object
if (isset($_GET ['q'])) {
    $q = $_GET ['q'];
    $q_arr = explode("/", $q);
    $controller = $q_arr [0];
    // controller specific config and constants file include startf
    $constants_file = "config/" . $controller . "_constants.php";
    if (file_exists($constants_file)) {
        require_once ($constants_file);
    }

    $config_file = "config/" . $controller . "_config.php";
    if (file_exists($config_file)) {
        require_once ($config_file);
    }
}
/**
 * ====================================================
 * Loader object,controller class initialization
 * ====================================================
 */
$controller = $loader->createController(); // creates the requested controller object based on the 'controller' URL value
$controller->load = new Load ();
$controller->registry = new Registry();
$controller->executeAction(); // execute the requested controller's requested method based on the 'action' URL value. Controller methods output a View.

/**
 * ===========================
 * END of File index.php
 */
